apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - name: nginx-dev-v1
          imageVersion: 1.7.0
          namespace: nginx-dev-v1
          valuesFile: "helm-charts/values-dev.yaml"
        - name: nginx-dev-v2
          imageVersion: 1.7.0
          namespace: nginx-dev-v2
          valuesFile: "helm-charts/values-dev.yaml"
  template:
    metadata:
      name: '{{ .name }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true        
      sources:
        - repoURL: https://github.com/TanmayRao7/nginx-helm.git
          targetRevision: master
          path: nginx-chart 
          helm:
            valueFiles:
              - '{{ .valuesFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'